import { definePatternSet, type PatternSet } from "./pattern.js";
export const CS_PATTERNS: PatternSet = definePatternSet("cs", [
  { id: "ignore_previous", verb: "ignoruj|ignorujte|zapomen|zapomente", object: "(?:(?:vsechny|veskere)\\s+)?(?:predchozi|drivejsi|vyse\\s+uvedene)\\s+(?:instrukce|pokyny|pravidla|zadani|predpisy?|narizeni|direktivy?|prikazy)", note: "Ignorování předchozí autority" },
  { id: "override_policy", verb: "obejdi|obejdete|prepis|prepiste|zrus|zruste|potlac|potlacte", object: "systemovy\\s+prompt|systemove\\s+instrukce|bezpecnostni\\s+(?:politiku|pravidla|ochrany)|guardrails?|pokyny\\s+systemu", note: "Obejití systémových pravidel" },
  { id: "reveal_secret", verb: "prozrad|prozradte|odhal|odhalte|zobraz|zobrazte|vypis|vypiste|ukaz|ukazte", object: "systemovy\\s+prompt|skryte\\s+instrukce|api\\s+klic|token|heslo|prihlasovaci\\s+udaje|tajemstvi", note: "Odhalení skrytých dat", gap: 64 },
  { id: "role_switch", verb: "nyni\\s+jsi|ted\\s+jsi|od\\s+ted\\s+jsi|nyni\\s+jste|bud|budte|chovej\\s+se\\s+jako|chovejte\\s+se\\s+jako|jednej\\s+jako|jednejte\\s+jako", object: "asistent|system|developer|root|administrator|admin|spravce\\s+systemu", note: "Změna role modelu" },
  { id: "replacement_system", verb: "vytvor|vytvorte|udelej|udelejte|napis|napiste|nastav|nastavte|nahrad|nahradte", object: "(?:novy|nova|nove|novou|nahradni|nahrazujici)\\s+(?:systemovy\\s+prompt|instrukce|pokyny|pravidla|zadani|predpisy?|narizeni|direktivy?|direktivu|prikazy)", note: "Vytvoření náhradních pravidel" },
  { id: "follow_instead", verb: "od\\s+ted\\s+se\\s+rid|od\\s+ted\\s+se\\s+ridte|rid\\s+se|ridte\\s+se|se\\s+rid|se\\s+ridte|postupuj\\s+podle|postupujte\\s+podle", object: "(?:techto|temito|nasledujicich|nasledujicimi)\\s+(?:instrukci|instrukce|instrukcemi|pokynu|pokyny|pravidel|pravidla|pravidly|prikazu|prikazy)(?:\\s+misto\\s+predchozich)?", note: "Přesměrování na nové instrukce" },
  { id: "model_must", verb: "(?:asistent|model|llm)\\s+(?:musi|ma)\\s+(?:ignorovat|obejit|prozradit|vykonat|spustit|odeslat|poslat)", object: "instrukce|pokyny|pravidla|systemovy\\s+prompt|prikaz|tajemstvi|token|prihlasovaci\\s+udaje|data", note: "Příkaz adresovaný modelu" },
  { id: "exfiltrate", verb: "odesli|odeslete|posli|poslete|nahraj|nahrajte|vyexportuj|vyexportujte", object: "tajemstvi|token|prihlasovaci\\s+udaje|heslo|api\\s+klic|systemovy\\s+prompt", note: "Exfiltrace citlivých dat", gap: 56 },
]);
