import { definePatternSet, type PatternSet } from "./pattern.js";
export const DE_PATTERNS: PatternSet = definePatternSet("de", [
  { id: "ignore_previous", verb: "ignoriere|ignoriert|ignorieren\\s+sie|vergiss|vergesst|vergessen\\s+sie", object: "(?:(?:alle|die)\\s+)?(?:vorherigen|bisherigen|obigen)\\s+(?:anweisungen|regeln|vorgaben|vorschriften|befehle|nachrichten)", note: "Vorherige Autorität ignorieren" },
  { id: "override_policy", verb: "umgehe|umgeht|umgehen\\s+sie|uberschreibe|uberschreibt|uberschreiben\\s+sie|setze|setzen\\s+sie", object: "system-prompt|systemprompt|anweisungen|sicherheitsregeln|richtlinie(?:\\s+außer\\s+kraft)?|richtlinien|guardrails?", note: "Systemregeln umgehen" },
  { id: "reveal_secret", verb: "enthulle|enthullt|enthullen\\s+sie|zeige|zeigt|zeigen\\s+sie|drucke|druckt|drucken\\s+sie|gib|gebt|geben\\s+sie", object: "system-prompt|systemprompt|versteckte\\s+anweisungen|versteckten\\s+anweisungen|api-schlussel|api\\s+schlussel|token|passwort|zugangsdaten|geheimnis", note: "Verborgene Daten offenlegen", gap: 64 },
  { id: "role_switch", verb: "du\\s+bist\\s+jetzt|sie\\s+sind\\s+jetzt|sei|seid|seien\\s+sie|handle\\s+als|handelt\\s+als|handeln\\s+sie\\s+als", object: "assistent|system|developer|root|administrator|admin|systemadministrator", note: "Rollenwechsel" },
  { id: "replacement_system", verb: "erstelle|erstellt|erstellen\\s+sie|schreibe|schreibt|schreiben\\s+sie|setze|setzt|setzen\\s+sie|ersetze|ersetzt|ersetzen\\s+sie", object: "(?:einen?\\s+)?(?:neuen?|ersatz)\\s+(?:system-prompt|systemprompt|anweisungen|regeln|vorgaben|vorschriften|befehle)", note: "Ersatzregeln erstellen" },
  { id: "follow_instead", verb: "folge|folgt|folgen\\s+sie|befolge|befolgt|befolgen\\s+sie", object: "(?:diese|diesen|die\\s+folgenden|den\\s+folgenden)\\s+(?:anweisungen|regeln|vorgaben)\\s+stattdessen", note: "Neue Anweisungen stattdessen befolgen" },
  { id: "model_must", verb: "(?:assistent|modell|llm)\\s+(?:muss|soll)", object: "(?:anweisungen|regeln|richtlinie).{0,24}(?:ignorieren|umgehen)|(?:system-prompt|systemprompt).{0,24}enthullen|befehl.{0,24}ausfuhren|token.{0,24}senden|(?:geheimnis|zugangsdaten|daten).{0,24}(?:senden|exfiltrieren)", note: "Befehl an das Modell" },
  { id: "exfiltrate", verb: "sende|sendet|senden\\s+sie|lade|ladet|laden\\s+sie|exfiltriere|exfiltriert|exfiltrieren\\s+sie", object: "geheimnis|token|zugangsdaten|passwort|api-schlussel|api\\s+schlussel|system-prompt|systemprompt", note: "Sensible Daten exfiltrieren", gap: 56 },
]);
