import { definePatternSet, type PatternSet } from "./pattern.js";
export const ES_PATTERNS: PatternSet = definePatternSet("es", [
  { id: "ignore_previous", verb: "ignora|ignoren|ignore\\s+usted|olvida|olviden|olvide\\s+usted", object: "(?:(?:todas|las)\\s+)?(?:instrucciones|reglas|indicaciones|directivas|ordenes|mensajes)\\s+(?:anteriores|previas|previos)", note: "Ignorar autoridad previa" },
  { id: "override_policy", verb: "omite|omitan|omita\\s+usted|anula|anulen|anule\\s+usted|sobrescribe|sobrescriban|sobrescriba\\s+usted", object: "instrucciones|prompt\\s+del\\s+sistema|politica|reglas\\s+de\\s+seguridad|guardrails?|directivas\\s+del\\s+sistema", note: "Omitir reglas del sistema" },
  { id: "reveal_secret", verb: "revela|revelen|revele\\s+usted|muestra|muestren|muestre\\s+usted|imprime|impriman|imprima\\s+usted|expone|expongan", object: "prompt\\s+del\\s+sistema|instrucciones\\s+ocultas|clave\\s+api|token|contrasena|credenciales|secreto", note: "Revelar datos ocultos", gap: 64 },
  { id: "role_switch", verb: "ahora\\s+eres|desde\\s+ahora\\s+eres|ahora\\s+es\\s+usted|se\\s+ahora|sean|actua\\s+como|actuen\\s+como|actue\\s+usted\\s+como", object: "asistente|sistema|developer|root|administrador|admin|administrador\\s+del\\s+sistema", note: "Cambio de rol" },
  { id: "replacement_system", verb: "crea|creen|cree\\s+usted|escribe|escriban|escriba\\s+usted|establece|establezcan|reemplace|reemplaza|reemplacen", object: "(?:un|una)?\\s*(?:nuevo|nueva|nuevos|nuevas|sustituto|sustitutiva|sustitutivas)\\s+(?:prompt\\s+del\\s+sistema|instrucciones|reglas|indicaciones|directivas|ordenes)", note: "Crear reglas de reemplazo" },
  { id: "follow_instead", verb: "sigue|sigan|siga\\s+usted|obedece|obedezcan|obedezca\\s+usted", object: "(?:estas|las\\s+siguientes)\\s+(?:instrucciones|reglas|indicaciones|directivas)\\s+en\\s+su\\s+lugar", note: "Seguir nuevas instrucciones en su lugar" },
  { id: "model_must", verb: "(?:asistente|modelo|llm)\\s+(?:debe|deberia)\\s+(?:ignorar|omitir|revelar|ejecutar|enviar|exfiltrar)", object: "instrucciones|reglas|prompt\\s+del\\s+sistema|orden|secreto|token|credenciales|datos", note: "Orden dirigida al modelo" },
  { id: "exfiltrate", verb: "envia|envien|envie\\s+usted|sube|suban|suba\\s+usted|exfiltra|exfiltren|exfiltre\\s+usted", object: "secreto|token|credenciales|contrasena|clave\\s+api|prompt\\s+del\\s+sistema", note: "Exfiltrar datos sensibles", gap: 56 },
]);
