import { definePatternSet, type PatternSet } from "./pattern.js";
export const PL_PATTERNS: PatternSet = definePatternSet("pl", [
  { id: "ignore_previous", verb: "zignoruj|zignorujcie|prosze\\s+zignorowac|zapomnij|zapomnijcie|prosze\\s+zapomniec", object: "(?:(?:wszystkie|dotychczasowe)\\s+)?(?:poprzednie|poprzednich|wczesniejsze|wczesniejszych|powyzsze)\\s+(?:instrukcje|instrukcjach|polecenia|poleceniach|zasady|zasadach|wytyczne|wytycznych|przepisy|rozkazy|wiadomosci)", note: "Ignorowanie poprzedniego autorytetu" },
  { id: "override_policy", verb: "omin|omincie|prosze\\s+ominac|nadpisz|nadpiszcie|prosze\\s+nadpisac|wylacz|wylaczcie", object: "prompt\\s+systemowy|instrukcje\\s+systemowe|zasady\\s+bezpieczenstwa|polityke|polityki|guardrails?|wytyczne\\s+systemu", note: "Obejście reguł systemowych" },
  { id: "reveal_secret", verb: "ujawnij|ujawnijcie|prosze\\s+ujawnic|pokaz|pokazcie|prosze\\s+pokazac|wypisz|wypiszcie|prosze\\s+wypisac", object: "prompt\\s+systemowy|ukryte\\s+instrukcje|klucz\\s+api|token|haslo|dane\\s+uwierzytelniajace|sekret", note: "Ujawnienie ukrytych danych", gap: 64 },
  { id: "role_switch", verb: "od\\s+teraz\\s+jestes|teraz\\s+jestes|badz|badzcie|prosze\\s+byc|dzialaj\\s+jako|dzialajcie\\s+jako", object: "asystent|system|systemem|developer|root|rootem|administrator|administratorem|admin|administrator\\s+systemu", note: "Zmiana roli modelu" },
  { id: "replacement_system", verb: "utworz|utworzcie|prosze\\s+utworzyc|napisz|napiszcie|prosze\\s+napisac|ustaw|ustawcie|zastap|zastapcie", object: "(?:nowy|nowa|nowe|zastepczy|zastepcze)\\s+(?:prompt\\s+systemowy|instrukcje|polecenia|zasady|wytyczne|przepisy|rozkazy)", note: "Tworzenie zastępczych reguł" },
  { id: "follow_instead", verb: "od\\s+teraz\\s+stosuj|stosuj|stosujcie|prosze\\s+stosowac|postepuj\\s+wedlug|postepujcie\\s+wedlug", object: "(?:te|tych|tymi|nastepujacych)\\s+(?:instrukcji|instrukcje|polecen|polecenia|zasad|zasady|wytycznych|wytyczne)(?:\\s+zamiast\\s+poprzednich)?", note: "Stosowanie nowych instrukcji zamiast" },
  { id: "model_must", verb: "(?:asystent|model|llm)\\s+(?:musi|powinien)\\s+(?:ignorowac|ominac|ujawnic|wykonac|wyslac|eksfiltrowac)", object: "instrukcje|polecenia|zasady|prompt\\s+systemowy|rozkaz|sekret|token|dane\\s+uwierzytelniajace|dane", note: "Polecenie skierowane do modelu" },
  { id: "exfiltrate", verb: "wyslij|wyslijcie|prosze\\s+wyslac|przeslij|przeslijcie|prosze\\s+przeslac|eksfiltruj|eksfiltrujcie", object: "sekret|token|dane\\s+uwierzytelniajace|haslo|klucz\\s+api|prompt\\s+systemowy", note: "Eksfiltracja danych wrażliwych", gap: 56 },
]);
