import { definePatternSet, type PatternSet } from "./pattern.js";
export const SK_PATTERNS: PatternSet = definePatternSet("sk", [
  { id: "ignore_previous", verb: "ignoruj|ignorujte|zabudni|zabudnite", object: "(?:(?:vsetky|vsetkych)\\s+)?(?:predchadzajuce|predosle|vyssie\\s+uvedene)\\s+(?:instrukcie|pokyny|pravidla|zadanie|predpisy?|nariadenie|nariadenia|prikazy)", note: "Ignorovanie predchádzajúcej autority" },
  { id: "override_policy", verb: "obid|obidte|prepis|prepiste|zrus|zruste|potlac|potlacte", object: "systemovy\\s+prompt|systemove\\s+instrukcie|bezpecnostne\\s+(?:pravidla|ochrany|politiky)|guardrails?|pokyny\\s+systemu", note: "Obídenie systémových pravidiel" },
  { id: "reveal_secret", verb: "prezrad|prezradte|odhal|odhalte|zobraz|zobrazte|vypis|vypiste|ukaz|ukazte", object: "systemovy\\s+prompt|skryte\\s+instrukcie|api\\s+kluc|token|heslo|prihlasovacie\\s+udaje|tajomstvo", note: "Odhalenie skrytých dát", gap: 64 },
  { id: "role_switch", verb: "teraz\\s+si|odteraz\\s+si|teraz\\s+ste|bud|budte|spravaj\\s+sa\\s+ako|spravajte\\s+sa\\s+ako|konaj\\s+ako|konajte\\s+ako", object: "asistent|system|developer|root|administrator|admin|spravca\\s+systemu", note: "Zmena role modelu" },
  { id: "replacement_system", verb: "vytvor|vytvorte|urob|urobte|napis|napiste|nastav|nastavte|nahrad|nahradte", object: "(?:novy|nova|nove|nahradny|nahradne)\\s+(?:systemovy\\s+prompt|instrukcie|pokyny|pravidla|zadanie|predpisy?|nariadenie|prikazy)", note: "Vytvorenie náhradných pravidiel" },
  { id: "follow_instead", verb: "odteraz\\s+sa\\s+riad|odteraz\\s+sa\\s+riadte|riad\\s+sa|riadte\\s+sa|sa\\s+riad|sa\\s+riadte|postupuj\\s+podla|postupujte\\s+podla", object: "(?:tychto|tymito|nasledujucich|nasledujucimi)\\s+(?:instrukcii|instrukciami|pokynov|pokynmi|pravidiel|pravidlami|prikazov|prikazmi)(?:\\s+namiesto\\s+predchadzajucich)?", note: "Presmerovanie na nové inštrukcie" },
  { id: "model_must", verb: "(?:asistent|model|llm)\\s+(?:musi|ma)\\s+(?:ignorovat|obist|prezradit|vykonat|spustit|odoslat|poslat)", object: "instrukcie|pokyny|pravidla|systemovy\\s+prompt|prikaz|tajomstvo|token|prihlasovacie\\s+udaje|data", note: "Príkaz adresovaný modelu" },
  { id: "exfiltrate", verb: "odosli|odoslite|posli|poslite|nahraj|nahrajte|vyexportuj|vyexportujte", object: "tajomstvo|token|prihlasovacie\\s+udaje|heslo|api\\s+kluc|systemovy\\s+prompt", note: "Exfiltrácia citlivých dát", gap: 56 },
]);
